name: Build-Container-With-Ext-Action
on: [push]
permissions:
      id-token: write
      contents: read 
jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Build Container
        uses: sandrolex/docker-build@main
        with:
          image-name: http-server
      
      - name: Verify
        run: |
          docker images