name: Hello World Action
on: [push]
permissions:
      id-token: write
      contents: read 
jobs:
  call-workflow:
    uses: sandrolex/docker-build/.github/workflows/build-image.yml@main
    with:
      image-name: http-server:exp