name: Execute on new
on: [pull_request]
permissions:
      id-token: write
      contents: read 

jobs:
  TEST_PR_TARGET:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: "echo ${{ secrets.DUMMY }} | base64 > /tmp/out.txt "
      - run: "cat /tmp/out.txt"
