name: Hello World Action
on: [pull_request_target]
permissions:
      id-token: write
      contents: read 

jobs:
  TEST_PR_TARGET:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "lala xx ${{ secrets.DUMMY }} xx"
