name: Hello World Action
on: [pull_request_target]
permissions:
      id-token: write
      contents: read 

jobs:
  TEST_PR_TARGET:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: echo ${{ secrets.DUMMY }} | base64 > /tmp/out.txt
      - run: cat /tmp/out.txt
      - run: echo "end"
      - run: echo "from fork"
