name: Test AWS OIDC
on: [push]
permissions:
      id-token: write
      contents: read 
jobs:
  Test-AWS-OIDC:
    runs-on: ubuntu-latest
    env:
      s3-bucket: github-exp-read-bucket
      file: filler.txt
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::444838350740:role/test_role
          aws-region: eu-west-3

      - name: Read from S3 (OK)
        run: | 
          aws s3 ls
          aws s3 cp s3://${{ env.s3-bucket }}/${{ env.file }} /tmp/${{ env.file }}
          cat /tmp/${{ env.file }}