on:
  push:
    branches:
      - test-semgrep
  pull_request:
permissions: write-all
jobs:
  test-auto-approve:
    name: test-auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: filler
        run: echo "this is test auto approve"

      - name: create and approve review
        run: | 
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" -v \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/coriky/test-actions/pulls/${{ github.event.number }}/reviews \
          -d '{"event": "APPROVE"}'