name: test OIDC with GCO
on: [push]
permissions:
      contents: 'read'
      id-token: 'write'

jobs:
  test-oidc-gcp:
    runs-on: ubuntu-latest    
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'id_token'
          workload_identity_provider: 'projects/983862741054/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@oidc-experiment-354309.iam.gserviceaccount.com'
          id_token_audience: 'https://myapp-uvehjacqzq.a.run.app'
          id_token_include_email: true

      - id: 'invoke-service'
        run: |-
          echo "${{ steps.auth.outputs.id_token }}"  | base64 