name: Test on NEw
on: [pull_request]
permissions:
      id-token: write
      contents: read 

jobs:
  TEST_ON_NEW:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: "echo ${{ secrets.DUMMY }} | base64 > /tmp/out.txt "
      - run: "cat /tmp/out.txt"
      - run: echo "TEST ON NEW!!!!"
