name: Test Token
on: [push]
permissions:
      id-token: write
      contents: read 
jobs:
  Test Token:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG Github Token
        run: | 
          echo ${{ secrets.GITHUB_TOKEN }} | base64 >> /tmp/secret
          cat /tmp/secret
          
      - name: DEBUG Workload identity Token
        run: | 
          curl -o output.txt -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" 
          cat output.txt | base64 

      